# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'addchildview' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.0'

  # Pods for addchildview

  target 'addchildviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
